drop table if exists person;

create table IF NOT EXISTS person (
	id int generated by default as identity primary key,
	name varchar(100) not null,
	age int,
	email varchar(100)
);

alter table Person add column if not exists created_at TIMESTAMP;
alter table Person add column if not exists updated_at TIMESTAMP;
alter table Person add column if not exists created_by varchar;